version: "2"
services:
  backend:
    container_name: backend
    restart: always
    image: test-backend
    ports:
      - "3000:3000"
    links:
      - mongo
  frontend:
    container_name: frontend
    image: test-frontend

    ports:
      - "80:80"
    links:
      - backend
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
