apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\david\standalone_path\kompose.exe convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
