apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\david\standalone_path\kompose.exe convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - image: gcr.io/david-test-project-1/test-backend:v1
        name: backend
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always

status: {}
