---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: gcr.io/david-test-project-1/test-frontend:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: backend
    image: gcr.io/david-test-project-1/test-backend:v1
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
