apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: hello
          image: "test-backend"
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 3000
